name: lampstore
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  carousel_pro: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
   - images/
  #  - images/a_dot_ham.jpeg

  fonts:
    - family: Proxima
      fonts:
        - asset: fonts/ProximaNova-Regular.otf
        - asset: fonts/ProximaNova-Bold.otf
          weight: 700
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.otf
        - asset: fonts/Poppins-Bold.otf
          weight: 700
    - family: QuickSand
      fonts:
        - asset: fonts/Quicksand-Regular.otf
        - asset: fonts/Quicksand-Bold.otf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
